version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  web: &web
    build: .
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: enabled
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    command: rails server --port 3000 --binding "0.0.0.0"
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  webpacker:
    <<: *web
    command: ./bin/webpack-dev-server
    depends_on:
      - web
    ports:
      - "3035:3035"
