version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    environment:
      RAILS_ENV: production
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails server --port 3000 --binding 0.0.0.0"
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
